# Generated by Django 3.0.8 on 2020-07-09 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('coffe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.CoffeType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=8)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.CoffeeStock')),
            ],
        ),
    ]
