# Generated by Django 3.0.8 on 2020-07-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('logistics', '0002_auto_20200709_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeOrder',
            new_name='CoffeOrder',
        ),
        migrations.RenameModel(
            old_name='CoffeeStock',
            new_name='CoffeStock',
        ),
    ]
