# Generated by Django 3.0.8 on 2020-07-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20200710_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeorder',
            old_name='coffee_stock',
            new_name='coffe_stock',
        ),
    ]
